-- ============================================================================
-- Migration: Initial Schema for Flashcards AI
-- ============================================================================
-- Description: Creates the complete database schema for the Flashcards AI application
-- Author: Generated from db-plan.md
-- Date: 2025-12-10
--
-- This migration creates:
-- - Custom ENUM types (source_type, event_type)
-- - Core tables (profiles, decks, flashcards, generation_events)
-- - Indexes optimized for common query patterns
-- - Triggers for automatic profile creation and updated_at management
-- - Row Level Security (RLS) policies for data isolation
--
-- Affected tables: profiles, decks, flashcards, generation_events
-- Dependencies: Supabase Auth (auth.users)
-- Special considerations:
--   - Cascading deletes for GDPR compliance
--   - FSRS algorithm parameters stored in flashcards table
--   - Monthly AI generation limit tracked in profiles
-- ============================================================================


-- ============================================================================
-- SECTION 1: ENUM TYPES
-- ============================================================================

-- source_type: defines the origin of a flashcard
-- 'ai' = generated by AI, 'manual' = created by user
create type source_type as enum ('ai', 'manual');

-- event_type: tracks AI generation workflow events for analytics
-- 'GENERATED' = AI draft created
-- 'ACCEPTED' = draft accepted without changes
-- 'REJECTED' = draft discarded
-- 'EDITED' = draft modified before acceptance
create type event_type as enum ('GENERATED', 'ACCEPTED', 'REJECTED', 'EDITED');


-- ============================================================================
-- SECTION 2: TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table: profiles
-- ----------------------------------------------------------------------------
-- Stores application-specific user data (1:1 with auth.users)
--
-- Purpose:
--   - Track monthly AI flashcard generation limits (200 per month)
--   - Store user preferences and metadata
--   - Automatically created via trigger on user registration
--
-- Security: RLS enabled, users can only access their own profile
-- Deletion: Cascades from auth.users deletion (GDPR compliance)
-- ----------------------------------------------------------------------------
create table profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  monthly_ai_flashcards_count integer not null default 0 check (monthly_ai_flashcards_count >= 0),
  ai_limit_reset_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table profiles enable row level security;

-- Add table comment
comment on table profiles is 'User application profiles with AI generation tracking';
comment on column profiles.monthly_ai_flashcards_count is 'Number of AI flashcards generated in current month (max 200)';
comment on column profiles.ai_limit_reset_date is 'Date when the monthly limit was last reset';


-- ----------------------------------------------------------------------------
-- Table: decks
-- ----------------------------------------------------------------------------
-- Stores thematic flashcard collections
--
-- Purpose:
--   - Organize flashcards into topic-based decks
--   - Each user can have unlimited decks
--   - Deck names must be unique per user
--
-- Security: RLS enabled, users can only access their own decks
-- Deletion: Cascades to flashcards when deck is deleted
-- ----------------------------------------------------------------------------
create table decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(user_id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Ensure unique deck names per user
  unique(user_id, name)
);

-- Enable Row Level Security
alter table decks enable row level security;

-- Add table comment
comment on table decks is 'Thematic flashcard collections';
comment on column decks.name is 'Deck name (1-100 characters, unique per user)';


-- ----------------------------------------------------------------------------
-- Table: flashcards
-- ----------------------------------------------------------------------------
-- Stores educational flashcards with FSRS algorithm parameters
--
-- Purpose:
--   - Store flashcard content (front/back)
--   - Track FSRS spaced repetition parameters
--   - Support both AI-generated and manually created cards
--
-- FSRS Parameters:
--   - stability: memory stability (how well the card is remembered)
--   - difficulty: card difficulty rating
--   - elapsed_days: days since last review
--   - scheduled_days: days until next scheduled review
--   - reps: number of successful reviews
--   - lapses: number of failed reviews
--   - state: card state (0=new, 1=learning, 2=review, 3=relearning)
--
-- Security: RLS enabled, users access via deck ownership
-- Deletion: Cascades from deck deletion
-- ----------------------------------------------------------------------------
create table flashcards (
  id uuid primary key default gen_random_uuid(),
  deck_id uuid not null references decks(id) on delete cascade,
  front text not null check (char_length(front) between 1 and 200),
  back text not null check (char_length(back) between 1 and 500),
  source source_type not null,

  -- FSRS algorithm parameters
  stability real default 0.0,
  difficulty real default 0.0,
  elapsed_days integer default 0,
  scheduled_days integer default 0,
  reps integer default 0,
  lapses integer default 0,
  state smallint default 0 check (state between 0 and 3),

  -- Review scheduling
  last_review timestamptz,
  next_review timestamptz not null default now(),

  -- Metadata
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table flashcards enable row level security;

-- Add table comments
comment on table flashcards is 'Educational flashcards with FSRS spaced repetition parameters';
comment on column flashcards.front is 'Front of flashcard (question, max 200 chars)';
comment on column flashcards.back is 'Back of flashcard (answer, max 500 chars)';
comment on column flashcards.source is 'Origin of flashcard: ai or manual';
comment on column flashcards.state is 'FSRS state: 0=new, 1=learning, 2=review, 3=relearning';
comment on column flashcards.next_review is 'Next scheduled review date (default: immediate for new cards)';


-- ----------------------------------------------------------------------------
-- Table: generation_events
-- ----------------------------------------------------------------------------
-- Logs AI flashcard generation events for analytics
--
-- Purpose:
--   - Track AI generation workflow metrics
--   - Calculate acceptance rates and AI usage statistics
--   - Group events by generation session
--
-- Event Types:
--   - GENERATED: AI draft created (flashcard_id is NULL)
--   - ACCEPTED: draft accepted without changes (flashcard_id set)
--   - REJECTED: draft discarded (flashcard_id is NULL)
--   - EDITED: draft modified before acceptance (flashcard_id set)
--
-- Security: RLS enabled, users can only access their own events
-- Deletion: Preserves events even when flashcard is deleted (SET NULL)
-- ----------------------------------------------------------------------------
create table generation_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(user_id) on delete cascade,

  -- Nullable FK: NULL for GENERATED/REJECTED, set for ACCEPTED/EDITED
  flashcard_id uuid references flashcards(id) on delete set null,

  -- Groups all events from a single generation session
  generation_id uuid,

  event_type event_type not null,
  created_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table generation_events enable row level security;

-- Add table comments
comment on table generation_events is 'Analytics logs for AI flashcard generation workflow';
comment on column generation_events.flashcard_id is 'NULL for GENERATED/REJECTED, set for ACCEPTED/EDITED events';
comment on column generation_events.generation_id is 'Groups all events from a single generation session';


-- ============================================================================
-- SECTION 3: INDEXES
-- ============================================================================
-- Indexes optimized for common query patterns

-- Index for fetching review queue from specific deck
-- Used by: SELECT * FROM flashcards WHERE deck_id = ? AND next_review <= NOW()
-- This composite index supports both single-deck and multi-deck review queries
create index idx_flashcards_review_queue on flashcards(deck_id, next_review);

-- Index for listing user's decks chronologically
-- Used by: SELECT * FROM decks WHERE user_id = ? ORDER BY created_at DESC
create index idx_decks_user on decks(user_id, created_at desc);

-- Index for analytics queries on generation events
-- Used by: Acceptance rate calculations, AI usage statistics
create index idx_generation_events_analytics on generation_events(user_id, event_type, created_at desc);

-- Index for grouping events by generation session
-- Used by: SELECT * FROM generation_events WHERE generation_id = ?
create index idx_generation_events_session on generation_events(generation_id);


-- ============================================================================
-- SECTION 4: TRIGGERS AND FUNCTIONS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Function: create_profile_for_user
-- ----------------------------------------------------------------------------
-- Automatically creates a profile when a new user registers via Supabase Auth
--
-- Trigger: AFTER INSERT on auth.users
-- Security: SECURITY DEFINER allows INSERT bypassing RLS
-- ----------------------------------------------------------------------------
create or replace function create_profile_for_user()
returns trigger
security definer
set search_path = ''
language plpgsql
as $$
begin
  insert into public.profiles (user_id, created_at, updated_at)
  values (
    new.id,
    now(),
    now()
  );
  return new;
end;
$$;

-- Trigger on auth.users table
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function create_profile_for_user();


-- ----------------------------------------------------------------------------
-- Function: update_updated_at_column
-- ----------------------------------------------------------------------------
-- Universal function to automatically update the updated_at timestamp
--
-- Trigger: BEFORE UPDATE on tables with updated_at column
-- ----------------------------------------------------------------------------
create or replace function update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Trigger for profiles table
create trigger update_profiles_updated_at
  before update on profiles
  for each row
  execute function update_updated_at_column();

-- Trigger for decks table
create trigger update_decks_updated_at
  before update on decks
  for each row
  execute function update_updated_at_column();

-- Trigger for flashcards table
create trigger update_flashcards_updated_at
  before update on flashcards
  for each row
  execute function update_updated_at_column();


-- ============================================================================
-- SECTION 5: ROW LEVEL SECURITY POLICIES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- RLS Policies: profiles
-- ----------------------------------------------------------------------------
-- Security model: Users can only access their own profile
-- Note: INSERT blocked by design (profiles created only via trigger)
-- Note: DELETE blocked by design (profiles deleted only via CASCADE)
-- ----------------------------------------------------------------------------

-- SELECT: Users can view their own profile
create policy "Users can view own profile"
  on profiles
  for select
  to authenticated
  using (user_id = auth.uid());

-- UPDATE: Users can update their own profile
create policy "Users can update own profile"
  on profiles
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());


-- ----------------------------------------------------------------------------
-- RLS Policies: decks
-- ----------------------------------------------------------------------------
-- Security model: Users have full CRUD access to their own decks
-- Anonymous users: No access
-- ----------------------------------------------------------------------------

-- SELECT: Users can view their own decks
create policy "Users can view own decks"
  on decks
  for select
  to authenticated
  using (user_id = auth.uid());

-- INSERT: Users can create decks for themselves
create policy "Users can create own decks"
  on decks
  for insert
  to authenticated
  with check (user_id = auth.uid());

-- UPDATE: Users can update their own decks
create policy "Users can update own decks"
  on decks
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- DELETE: Users can delete their own decks
-- WARNING: This will cascade delete all flashcards in the deck
create policy "Users can delete own decks"
  on decks
  for delete
  to authenticated
  using (user_id = auth.uid());


-- ----------------------------------------------------------------------------
-- RLS Policies: flashcards
-- ----------------------------------------------------------------------------
-- Security model: Users access flashcards via deck ownership
-- Access verified through EXISTS subquery checking deck ownership
-- Anonymous users: No access
-- ----------------------------------------------------------------------------

-- SELECT: Users can view flashcards from their own decks
create policy "Users can view flashcards from own decks"
  on flashcards
  for select
  to authenticated
  using (
    exists (
      select 1
      from decks
      where decks.id = flashcards.deck_id
        and decks.user_id = auth.uid()
    )
  );

-- INSERT: Users can create flashcards in their own decks
create policy "Users can create flashcards in own decks"
  on flashcards
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from decks
      where decks.id = flashcards.deck_id
        and decks.user_id = auth.uid()
    )
  );

-- UPDATE: Users can update flashcards in their own decks
-- Note: Editing content does not reset FSRS parameters
create policy "Users can update flashcards in own decks"
  on flashcards
  for update
  to authenticated
  using (
    exists (
      select 1
      from decks
      where decks.id = flashcards.deck_id
        and decks.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from decks
      where decks.id = flashcards.deck_id
        and decks.user_id = auth.uid()
    )
  );

-- DELETE: Users can delete flashcards from their own decks
create policy "Users can delete flashcards from own decks"
  on flashcards
  for delete
  to authenticated
  using (
    exists (
      select 1
      from decks
      where decks.id = flashcards.deck_id
        and decks.user_id = auth.uid()
    )
  );


-- ----------------------------------------------------------------------------
-- RLS Policies: generation_events
-- ----------------------------------------------------------------------------
-- Security model: Users can only view and create their own events
-- Events are immutable (no UPDATE policy)
-- Events are deleted only via CASCADE (no DELETE policy)
-- Anonymous users: No access (analytics only for authenticated users)
-- ----------------------------------------------------------------------------

-- SELECT: Users can view their own generation events
create policy "Users can view own generation events"
  on generation_events
  for select
  to authenticated
  using (user_id = auth.uid());

-- INSERT: Users can create generation events for themselves
create policy "Users can create own generation events"
  on generation_events
  for insert
  to authenticated
  with check (user_id = auth.uid());


-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
-- Summary:
--   - 2 ENUM types created
--   - 4 tables created with RLS enabled
--   - 5 indexes created for query optimization
--   - 3 functions and 4 triggers created
--   - 14 RLS policies created (granular per operation and role)
--
-- Next steps:
--   1. Verify migration: Run verification queries from db-plan.md section 9.2
--   2. Generate TypeScript types: supabase gen types typescript
--   3. Test RLS policies with different users
--   4. Seed test data for development
-- ============================================================================
